/*
 * Copyright (c) 2002-2003 by OpenSymphony
 * All rights reserved.
 */
/*
 * Generated by XDoclet - Do not edit!
 */
package com.opensymphony.module.sequence;


/**
 * Local interface for Sequence.
 * @author <a href="mailto:joe@truemesh.com">Joe Walnes</a>
 * @author <a href="mailto:hani@formicary.net">Hani Suleiman</a>
 * @version $Revision: 127 $
 */
public interface SequenceLocal extends javax.ejb.EJBLocalObject {
    //~ Methods ////////////////////////////////////////////////////////////////

    public long getActualCount();

    public long getCount(int increment);

    public java.lang.String getName();
}
