/*
 * Copyright (c) 2002-2003 by OpenSymphony
 * All rights reserved.
 */
/*
 * Generated by XDoclet - Do not edit!
 */
package com.opensymphony.workflow.spi.ejb;


/**
 * Local interface for CurrentStep.
 * @author <a href="mailto:hani@formicary.net">Hani Suleiman</a>
 * @author <a href="mailto:plightbo@hotmail.com">Pat Lightbody</a>
 */
public interface CurrentStepLocal extends javax.ejb.EJBLocalObject, com.opensymphony.workflow.spi.ejb.AbstractLocalStep {
    //~ Methods ////////////////////////////////////////////////////////////////

    public void setActionId(int actionId);

    public int getActionId();

    public void setCaller(java.lang.String caller);

    public java.lang.String getCaller();

    public void setDueDate(java.sql.Timestamp dueDate);

    public java.sql.Timestamp getDueDate();

    public long getEntryId();

    public void setFinishDate(java.sql.Timestamp finishDate);

    public java.sql.Timestamp getFinishDate();

    public java.lang.Long getId();

    public java.lang.String getOwner();

    public java.sql.Timestamp getStartDate();

    public void setStatus(java.lang.String status);

    public java.lang.String getStatus();

    public int getStepId();
}
