/*
 * Copyright (c) 2002-2003 by OpenSymphony
 * All rights reserved.
 */
/*
 * Generated by XDoclet - Do not edit!
 */
package com.opensymphony.workflow.spi.ejb;


/**
 * Local interface for WorkflowEntry.
 * @author <a href="mailto:hani@formicary.net">Hani Suleiman</a>
 * @author <a href="mailto:plightbo@hotmail.com">Pat Lightbody</a>
 */
public interface WorkflowEntryLocal extends javax.ejb.EJBLocalObject {
    //~ Methods ////////////////////////////////////////////////////////////////

    public java.lang.Long getId();

    public void setState(int state);

    public int getState();

    public java.lang.String getWorkflowName();
}
