/*
 * Copyright (c) 2002-2003 by OpenSymphony
 * All rights reserved.
 */
/*
 * Generated by XDoclet - Do not edit!
 */
package com.opensymphony.workflow.spi.ejb;


/**
 * Session layer for WorkflowStore.
 * @author <a href="mailto:hani@formicary.net">Hani Suleiman</a>
 * @version $Revision: 1.3 $ Date: Apr 7, 2003 Time: 10:57:28 PM
 */
public class WorkflowStoreSession extends com.opensymphony.workflow.spi.ejb.WorkflowStoreSessionEJB implements javax.ejb.SessionBean {
    //~ Methods ////////////////////////////////////////////////////////////////

    public void setSessionContext(javax.ejb.SessionContext ctx) {
    }

    public void ejbActivate() {
    }

    public void ejbCreate() throws javax.ejb.CreateException {
    }

    public void ejbPassivate() {
    }

    public void ejbRemove() {
    }

    public void unsetSessionContext() {
    }
}
