/*
 * Copyright (c) 2002-2003 by OpenSymphony
 * All rights reserved.
 */
/*
 * Generated by XDoclet - Do not edit!
 */
package com.opensymphony.workflow.spi.ejb;


/**
 * Local home interface for WorkflowEntry.
 * @author <a href="mailto:hani@formicary.net">Hani Suleiman</a>
 * @author <a href="mailto:plightbo@hotmail.com">Pat Lightbody</a>
 */
public interface WorkflowEntryLocalHome extends javax.ejb.EJBLocalHome {
    //~ Static fields/initializers /////////////////////////////////////////////

    public static final String COMP_NAME = "java:comp/env/ejb/WorkflowEntry";
    public static final String JNDI_NAME = "WorkflowEntry";

    //~ Methods ////////////////////////////////////////////////////////////////

    public com.opensymphony.workflow.spi.ejb.WorkflowEntryLocal create(java.lang.String workflowName) throws javax.ejb.CreateException;

    public com.opensymphony.workflow.spi.ejb.WorkflowEntryLocal findByPrimaryKey(java.lang.Long pk) throws javax.ejb.FinderException;
}
