/*
 * Copyright (c) 2002-2003 by OpenSymphony
 * All rights reserved.
 */
/*
 * Generated by XDoclet - Do not edit!
 */
package com.opensymphony.workflow.spi.ejb;


/**
 * Home interface for WorkflowStore.
 * @author <a href="mailto:hani@formicary.net">Hani Suleiman</a>
 * @version $Revision: 1.3 $ Date: Apr 7, 2003 Time: 10:57:28 PM
 */
public interface WorkflowStoreHome extends javax.ejb.EJBHome {
    //~ Methods ////////////////////////////////////////////////////////////////

    //public static final String COMP_NAME="java:comp/env/ejb/WorkflowStore";
    //public static final String JNDI_NAME="WorkflowStore";
    public com.opensymphony.workflow.spi.ejb.WorkflowStoreRemote create() throws javax.ejb.CreateException, java.rmi.RemoteException;
}
