/*
 * Copyright (c) 2002-2003 by OpenSymphony
 * All rights reserved.
 */
/*
 * Generated by XDoclet - Do not edit!
 */
package com.opensymphony.workflow.ejb;


/**
 * Session layer for Workflow.
 * @author <a href="mailto:plightbo@hotmail.com">Pat Lightbody</a>
 * @author <a href="mailto:hani@formicary.net">Hani Suleiman</a>
 * @version $Revision: 1.7 $
 */
public class WorkflowSession extends com.opensymphony.workflow.ejb.WorkflowEJB implements javax.ejb.SessionBean {
    //~ Methods ////////////////////////////////////////////////////////////////

    public void setSessionContext(javax.ejb.SessionContext ctx) {
        super.setSessionContext(ctx);
    }

    public void ejbActivate() {
    }

    public void ejbPassivate() {
    }

    public void ejbRemove() {
    }

    public void unsetSessionContext() {
    }
}
