/*
 * Copyright (c) 2002-2003 by OpenSymphony
 * All rights reserved.
 */
/*
 * Generated by XDoclet - Do not edit!
 */
package com.opensymphony.workflow.spi.ejb;


/**
 * Local interface for CurrentStepPrev.
 * @author Hani Suleiman (hani@formicary.net) Date: Apr 7, 2003 Time: 8:17:26 PM
 */
public interface CurrentStepPrevLocal extends javax.ejb.EJBLocalObject {
    //~ Methods ////////////////////////////////////////////////////////////////

    public java.lang.Long getId();

    public java.lang.Long getPreviousId();
}
