/*
 * Copyright (c) 2002-2003 by OpenSymphony
 * All rights reserved.
 */
/*
 * Generated by XDoclet - Do not edit!
 */
package com.opensymphony.workflow.spi.ejb;


/**
 * CMP layer for HistoryStepPrev.
 * @author Hani Suleiman (hani@formicary.net) Date: Apr 7, 2003 Time: 8:17:09 PM
 */
public abstract class HistoryStepPrevCMP extends com.opensymphony.workflow.spi.ejb.PreviousHistoryStepEJB implements javax.ejb.EntityBean {
    //~ Methods ////////////////////////////////////////////////////////////////

    public void setEntityContext(javax.ejb.EntityContext ctx) {
    }

    public abstract void setId(java.lang.Long id);

    public abstract java.lang.Long getId();

    public abstract void setPreviousId(java.lang.Long previousId);

    public abstract java.lang.Long getPreviousId();

    public void ejbActivate() {
    }

    public void ejbLoad() {
    }

    public void ejbPassivate() {
    }

    public void ejbRemove() throws javax.ejb.RemoveException {
    }

    public void ejbStore() {
    }

    public void unsetEntityContext() {
    }
}
