/*
 * Copyright (c) 2002-2003 by OpenSymphony
 * All rights reserved.
 */
/*
 * Generated by XDoclet - Do not edit!
 */
package com.opensymphony.workflow.spi.ejb;


/**
 * Remote interface for WorkflowStore.
 * @author <a href="mailto:hani@formicary.net">Hani Suleiman</a>
 * @version $Revision: 1.3 $ Date: Apr 7, 2003 Time: 10:57:28 PM
 */
public interface WorkflowStoreRemote extends javax.ejb.EJBObject {
    //~ Methods ////////////////////////////////////////////////////////////////

    public void setEntryState(long entryId, int state) throws com.opensymphony.workflow.StoreException, java.rmi.RemoteException;

    public com.opensymphony.workflow.spi.Step createCurrentStep(long entryId, int stepId, java.lang.String owner, java.util.Date startDate, java.util.Date dueDate, java.lang.String status, long[] previousIds) throws com.opensymphony.workflow.StoreException, java.rmi.RemoteException;

    public com.opensymphony.workflow.spi.WorkflowEntry createEntry(java.lang.String workflowName) throws com.opensymphony.workflow.StoreException, java.rmi.RemoteException;

    public java.util.List findCurrentSteps(long entryId) throws com.opensymphony.workflow.StoreException, java.rmi.RemoteException;

    public com.opensymphony.workflow.spi.WorkflowEntry findEntry(long entryId) throws com.opensymphony.workflow.StoreException, java.rmi.RemoteException;

    public java.util.List findHistorySteps(long entryId) throws com.opensymphony.workflow.StoreException, java.rmi.RemoteException;

    public com.opensymphony.workflow.spi.Step markFinished(com.opensymphony.workflow.spi.Step step, int actionId, java.util.Date finishDate, java.lang.String status, java.lang.String caller) throws com.opensymphony.workflow.StoreException, java.rmi.RemoteException;

    public void moveToHistory(com.opensymphony.workflow.spi.Step step) throws com.opensymphony.workflow.StoreException, java.rmi.RemoteException;

    public java.util.List query(com.opensymphony.workflow.query.WorkflowQuery query) throws com.opensymphony.workflow.StoreException, java.rmi.RemoteException;

    public java.util.List query(com.opensymphony.workflow.query.WorkflowExpressionQuery query) throws com.opensymphony.workflow.StoreException, java.rmi.RemoteException;
}
