/*
 * Copyright (c) 2002-2003 by OpenSymphony
 * All rights reserved.
 */
/*
 * Generated by XDoclet - Do not edit!
 */
package com.opensymphony.workflow.spi.ejb;


/**
 * CMP layer for WorkflowEntry.
 * @author <a href="mailto:hani@formicary.net">Hani Suleiman</a>
 * @author <a href="mailto:plightbo@hotmail.com">Pat Lightbody</a>
 */
public abstract class WorkflowEntryCMP extends com.opensymphony.workflow.spi.ejb.WorkflowEntryEJB implements javax.ejb.EntityBean {
    //~ Methods ////////////////////////////////////////////////////////////////

    public void setEntityContext(javax.ejb.EntityContext ctx) {
    }

    public abstract void setId(java.lang.Long id);

    public abstract java.lang.Long getId();

    public abstract void setState(int state);

    public abstract int getState();

    public abstract void setWorkflowName(java.lang.String workflowName);

    public abstract java.lang.String getWorkflowName();

    public void ejbActivate() {
    }

    public void ejbLoad() {
    }

    public void ejbPassivate() {
    }

    public void ejbRemove() throws javax.ejb.RemoveException {
    }

    public void ejbStore() {
    }

    public void unsetEntityContext() {
    }
}
