/*
 * Copyright (c) 2002-2003 by OpenSymphony
 * All rights reserved.
 */
/*
 * Generated by XDoclet - Do not edit!
 */
package com.opensymphony.module.sequence;


/**
 * Home interface for SequenceGenerator.
 * @author <a href="mailto:joe@truemesh.com">Joe Walnes</a>
 * @author <a href="mailto:hani@formicary.net">Hani Suleiman</a>
 * @version $Revision: 130 $
 */
public interface SequenceGeneratorHome extends javax.ejb.EJBHome {
    //~ Methods ////////////////////////////////////////////////////////////////

    //public static final String COMP_NAME="java:comp/env/ejb/SequenceGenerator";
    //public static final String JNDI_NAME="SequenceGenerator";
    public com.opensymphony.module.sequence.SequenceGenerator create() throws javax.ejb.CreateException, java.rmi.RemoteException;
}
